### ISSUE TITLE
links fenced with backticks are not detected 

### ISSUE THREAD

**Issue by hellt** [microsoft/vscode-markdown-languageservice#70] opened 2022-10-14 09:25 UTC
A link such as [`monospaced`][link1] are not detected by vscode markdown services and removed during "organize link definitions" source action

[link1]: #someref

```
[`monospaced`][link1]

[link1]: #someref
```

![2022-10-14_11-23-14 (1)](https://user-images.githubusercontent.com/5679861/195812209-8d3cb1a5-5ae1-40f3-b1bf-103db9849c06.gif)

**Comment by mjbvz** [comment] 2022-10-14 14:55
Duplicate of #66

**Closed by mjbvz** 2022-10-14 14:55 UTC
